#backend = "xrender";
backend = "glx";

corner-radius = 13.0;


rounded-corners-rule = [
    "0:class_g = 'Urxvt'"
];

rounded-corners-exclude = [
   # "widthb > 1365 && heightb > 736" # For smart gaps and a non-floating bar
#    "class_g = 'Dunst'",
    "class_g = 'eww-left'",
    "class_g = 'eww-top'",
    "class_g = 'eww-filler'"
];


shadow = true;
shadow-radius = 20;
shadow-opacity = 0.4;
shadow-offset-x = -24;
shadow-offset-y = -16;
shadow-exclude = [
    "class_g = 'peek'",
    "class_g = 'Peek'",
    "class_g = 'eww-left'",
    "class_g = 'eww-top'",
    "class_g = 'eww-filler'",
    "class_g = 'MuseScore4Development'",
    "class_g = 'GLava'"
];

fading = true;
fade-in-step = 0.08;
fade-out-step = 0.08;
fade-exclude = [ ];
